export const ALL_PRODUCTS_START = 'ALL_PRODUCTS_START';
export const ALL_PRODUCTS_SUCCESS = 'ALL_PRODUCTS_SUCCESS';
export const ALL_PRODUCTS_FAIL = 'ALL_PRODUCTS_FAIL';

export const ACTIVE_PRODUCT_START = 'ACTIVE_PRODUCT_START';
export const ACTIVE_PRODUCT_SUCCESS = 'ACTIVE_PRODUCT_SUCCESS';
export const ACTIVE_PRODUCT_FAIL = 'ACTIVE_PRODUCT_FAIL';
