export const ALL_PRODUCTS_START = 'ALL_PRODUCTS_START';
export const ALL_PRODUCTS_SUCCESS = 'ALL_PRODUCTS_SUCCESS';
export const ALL_PRODUCTS_FAIL = 'ALL_PRODUCTS_FAIL';

export const ACTIVE_PRODUCT_START = 'ACTIVE_PRODUCT_START';
export const ACTIVE_PRODUCT_SUCCESS = 'ACTIVE_PRODUCT_SUCCESS';
export const ACTIVE_PRODUCT_FAIL = 'ACTIVE_PRODUCT_FAIL';

export const PRODUCTS_BY_TAG_START = 'PRODUCTS_BY_TAG_START';
export const PRODUCTS_BY_TAG_SUCCESS = 'PRODUCTS_BY_TAG_SUCCESS';
export const PRODUCTS_BY_TAG_FAIL = 'PRODUCTS_BY_TAG_FAIL';

export const PRODUCTS_BY_VENDOR_START = 'PRODUCTS_BY_VENDOR_START';
export const PRODUCTS_BY_VENDOR_SUCCESS = 'PRODUCTS_BY_VENDOR_SUCCESS';
export const PRODUCTS_BY_VENDOR_FAIL = 'PRODUCTS_BY_VENDOR_FAIL';
