export const ALL_COLLECTIONS_START = 'ALL_COLLECTIONS_START';
export const ALL_COLLECTIONS_SUCCESS = 'ALL_COLLECTIONS_SUCCESS';
export const ALL_COLLECTIONS_FAIL = 'ALL_COLLECTIONS_FAIL';

export const ACTIVE_COLLECTION_START = 'ACTIVE_COLLECTION_START';
export const ACTIVE_COLLECTION_SUCCESS = 'ACTIVE_COLLECTION_SUCCESS';
export const ACTIVE_COLLECTION_FAIL = 'ACTIVE_COLLECTION_FAIL';
